### ISSUE TITLE
Certificate problem for secure http request on valhalla.mapzen.com (missing intermediate CA)

### ISSUE THREAD

**Issue by dmeignan** [valhalla/tyr#117]
Not sure if this issue goes here but, here it is.

I am developing an Android app with turn-by-turn requests on `valhalla.mapzen.com`. When I want to use a secure http connection using `https://valhalla.mapzen.com` I obtain a security exception. (Note that normal unsecure requests work fine.)

It seems that the server configuration is missing an intermediate CA. Configuration can be checked at: [https://www.digicert.com/help/?host=valhalla.mapzen.com](https://www.digicert.com/help/?host=valhalla.mapzen.com) (Note that a solution is also given for configuring the server.)

Unfortunately, this problem raises an error when using the `HttpsURLConnection` on Android (see [http://developer.android.com/training/articles/security-ssl.html#MissingCa](http://developer.android.com/training/articles/security-ssl.html#MissingCa) for this particular case).

And just for information, the stack trace of the raised exception:

> Problem with HTTP connection.
>                                                                           javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
>                                                                               at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:322)
>                                                                               at com.android.okhttp.Connection.upgradeToTls(Connection.java:201)
>                                                                               at com.android.okhttp.Connection.connect(Connection.java:155)
>                                                                               at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
>                                                                               at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
>                                                                               at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
>                                                                               at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
>                                                                               at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
>                                                                               at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)

**Comment by dmeignan** [comment]
Sorry, it seems that the problem is related to our local network.
The app is not able to establish secure connection to `valhalla.mapzen.com` within our network, but it work fine from other networks. I should have check our servers before reporting the issue.
